# Generated by Django 4.2.4 on 2023-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('accountType', models.CharField(max_length=100)),
                ('monthlySpend', models.IntegerField()),
                ('userType', models.CharField(choices=[('new', 'New User'), ('client', 'Client')], default='new', max_length=10)),
                ('dateBooked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('market', models.CharField(max_length=50)),
                ('totalStock', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('objectif', models.TextField()),
                ('stockAvailable', models.BooleanField()),
                ('userType', models.CharField(choices=[('new', 'New User'), ('client', 'Client')], default='new', max_length=10)),
                ('meetingStatus', models.CharField(choices=[('waiting', 'waiting'), ('success', 'success'), ('failed', 'failed')], default='waiting', max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dateBooked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('visit_date', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
